using System;
using PizzaWorld.MVVM.Models;

namespace PizzaWorld.Services;

public class PizzaService
{
    private readonly static IEnumerable<Pizza> _pizzas = new List<Pizza>
{
    new Pizza { Name = "Pepperoni", Image = "pizza.png", Price = 9.9 , Description ="Pepperoni is an American variety of spicy, cured sausage made from pork and beef, seasoned with paprika, chili peppers, and garlic. It is characterized by a bright red color, fine-grained texture, and a soft, slightly smoky, and savory taste. It is a popular pizza topping that often curls into crisp cups when baked.Key Characteristics & Ingredients:Ingredients: Primarily a mix of pork and beef, though 100% beef versions exist.Flavor Profile: Mildly spicy and smoky, largely derived from paprika, black pepper, and garlic.Texture: Soft and slightly chewy before cooking, becoming crisp on the edges when baked.Appearance: Bright red due to the addition of paprika.Production: It is a fermented and dried sausage, similar to Southern Italian salami."},
    new Pizza { Name = "Margherita", Image = "pizza1.png", Price = 8.9 ,Description ="Margherita pizza is a classic Neapolitan pizza defined by its simplicity and fresh ingredients, representing the colors of the Italian flag: red tomatoes, white mozzarella, and green basil. It features a thin crust with a raised edge (cornicione), tangy tomato sauce, fresh mozzarella (often fior di latte or buffalo), extra virgin olive oil, and fresh basil leaves.Key Characteristics:Toppings: San Marzano tomato sauce, fresh mozzarella slices, fresh basil leaves, and a drizzle of olive oil.Crust: Thin, crispy-yet-chewy dough with slight charring, usually cooked in a high-temperature wood-fired oven.Flavor Profile: Light, fresh, and slightly sweet/tangy from the tomatoes and fresh cheese.Origin: Created in 1889 by Raffaele Esposito in Naples to honor Queen Margherita of Savoy." },
    new Pizza { Name = "Hawaiian", Image = "pizza2.png", Price = 10.9 ,Description ="Hawaiian pizza is a controversial yet popular pizza variety characterized by its sweet and savory flavor profile, combining tomato sauce, mozzarella cheese, and toppings of pineapple chunks and ham or bacon. Invented in Canada in 1962, this pizza offers a distinct contrast between the acidic, sweet fruit and salty meat"  },
    new Pizza { Name = "Veggie", Image = "pizza3.png", Price = 9.4 ,Description ="A veggie pizza is a vibrant, meat-free dish featuring a crisp or chewy crust topped with savory tomato sauce, melted mozzarella, and a colorful array of fresh vegetables. Common toppings include bell peppers, onions, mushrooms, tomatoes, olives, and artichokes, offering a fresh, balanced, and savory flavor profile.Key CharacteristicsCrust: Ranging from thin-and-crispy to thick, often made with traditional pizza dough or sometimes a buttery crescent roll dough.Sauce: Typically traditional tomato/pizza sauce, though creamy garlic sauce or pesto are popular variations.Toppings: A mix of fresh vegetables such as red onions, bell peppers, broccoli, zucchini, spinach, olives, artichoke hearts, and mushrooms.Cheese: Primarily mozzarella, often blended with parmesan or feta for added flavor."  },
    new Pizza { Name = "BBQ Chicken", Image = "pizza4.png", Price = 11.9 ,Description ="A BBQ chicken pizza is a savory-sweet, non-traditional pizza featuring a tangy BBQ sauce base, shredded chicken, mozzarella (or gouda), and sliced red onions, often topped with fresh cilantro. It typically offers a smoky, sweet, and tangy flavor profile on a crisp, airy crust, making it a popular homemade and restaurant favorite."  },
    new Pizza { Name = "Meat Lovers", Image = "pizza5.png", Price = 12.9,Description ="A meat lovers pizza is a hearty, indulgent pizza topped with a generous combination of savory meats—typically pepperoni, sausage, bacon, ham, and sometimes ground beef. It features a robust tomato sauce and thick mozzarella cheese on a sturdy crust designed to support the heavy, flavorful topping combination"  },
    new Pizza { Name = "Supreme", Image = "pizza6.png", Price = 13.9,Description ="A supreme pizza is a fully loaded pizza featuring a combination of popular meats and vegetables over mozzarella cheese and tomato sauce, often including pepperoni, sausage, onions, bell peppers, and mushrooms. It provides a hearty balance of savory, salty, and earthy flavors designed to be the ultimate pizza experience."  },
    new Pizza { Name = "Buffalo Chicken", Image = "pizza7.png", Price = 11.5,Description = "Buffalo chicken pizza is a zesty, savory pie that recreates the flavor of chicken wings, featuring shredded chicken tossed in spicy buffalo sauce, creamy ranch or blue cheese dressing, and melted mozzarella on a crisp crust. It is frequently topped with red onions and drizzled with extra hot sauce or blue cheese."  },
    new Pizza { Name = "Four Cheese", Image = "pizza8.png", Price = 10.5 ,Description = "A Pizza Quattro Formaggi (Four Cheese Pizza) is a classic Italian pizza characterized by a rich, savory combination of four distinct cheeses, typically melted over a white (bianca) or red (rossa) base. It features a creamy, gooey texture with a pungent, complex flavor profile, commonly using mozzarella, gorgonzola, fontina, and parmesan.Key CharacteristicsThe Cheese Mix: The classic combination is Mozzarella (base/moisture), Gorgonzola (tangy/bold), Fontina (creamy), and Parmigiano-Reggiano (sharp/salty).Base: Traditionally a pizza bianca (white pizza) with no tomato sauce, allowing the cheese flavors to shine, though some variations include a light red sauce.Texture & Taste: Exceptionally rich, gooey, and cheesy. The gorgonzola provides a distinct, savory tang, while the mozzarella ensures a perfect melt and cheese pull.Regional Variations: Other versions may substitute cheeses with Taleggio, Provolone, or Ricotta for extra creaminess." },

};

    public IEnumerable<Pizza> GetAllPizzas() => _pizzas;
    public IEnumerable<Pizza> GetPopularPizzas(int count = 6) => _pizzas.OrderBy(p => Guid.NewGuid()).Take(count);

    public IEnumerable<Pizza> SearchPizzas(string searchTerm) => string.IsNullOrWhiteSpace(searchTerm) ? _pizzas : _pizzas.Where(p => p.Name.Contains(searchTerm, StringComparison.OrdinalIgnoreCase));
}
